name: REACT_S3_gitaction

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
      - name: AWS IAM 사용자 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.ACCESS_KEY}}
          aws-secret-access-key: ${{secrets.SECRET_KEY}}
          aws-region: ap-northeast-2

      - name: node 버전 설정
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 캐싱 작업
        uses: actions/cache@v2
        with:
          path: cache
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn-lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-

      - name: yarn 설치
        run: npm install -g yarn
  
      - name: 리액트 패키지 설치
        run: yarn install
    
      - name: 리액트 빌드
        run: yarn build
        env:
          CI: false
      
      - name: S3 업로드
        run: aws s3 sync build/ s3://lv3-s3 --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.SECRET_KEY}}


          